---
version: "2"

services:

  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    #image: registry.senado.leg.br/adm/archivematica/archivematica-elasticsearch:1.13.2
    build:
      context: .
      dockerfile: jndiElasticsearch.Dockerfile
    # 1,4 GB
    mem_limit: 3200000000
    environment:
      cluster.name: am-cluster
      node.name: am-node
      network.host: 0.0.0.0
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=True"
      TZ: "America/Sao_Paulo"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/elasticsearch_data:/usr/share/elasticsearch/data:rw"
    ports:
      - 9200

  redis:
    image: "redis:3.2-alpine"
    #image: registry.senado.leg.br/adm/archivematica/archivematica-redis:1.12.1-sf01
    # 6 MB
    # mem_limit: 6000000
    command: '--save "" --appendonly no'  # Persistency disabled
    user: "redis"
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    ports:
      - 6379

  gearmand:
    image: "artefactual/gearmand:1.1.18-alpine"
    # image: registry.senado.leg.br/adm/archivematica/archivematica-gearmand:1.12.1-sf01
    # 50 MB
    mem_limit: 50000000
    command: "--queue-type=redis --redis-server=redis --redis-port=6379"
    user: "gearman"
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    ports:
      - 4730
    links:
      - "redis"

  fits:
    image: "artefactual/fits-ngserver:0.8.4"
    # image: registry.senado.leg.br/adm/archivematica/archivematica-fits:1.12.1-sf01
    # 500 MB
    mem_limit: 500000000
    ports:
      - 2113
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"  # Read and write needed!

  clamavd:
    image: "artefactual/clamav:latest"
    # image: registry.senado.leg.br/adm/archivematica/archivematica-clamav:1.12.1-sf01
    # 3.3 GB
    mem_limit: 3300000000
    #env_file: /mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/secrets/secrets-env.clamav.properties
    ports:
      - 3310
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"

  nginx:
    image: "nginx:1.18.0-alpine"
    # image: registry.senado.leg.br/adm/archivematica/archivematica-nginx:1.12.1-sf01
    # 7,5 MB
    mem_limit: 7500000
    # image: registry.senado.leg.br/infraweb/nginx:1.0.4
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/nginx/conf.d/archivematica.conf:/etc/nginx/conf.d/archivematica.conf:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 80
      - 8000

  archivematica-mcp-server:
    #image: registry.senado.leg.br/adm/archivematica/archivematica-mcp-server:1.13.2
    build: 
      context: .
      dockerfile: MCPServer.Dockerfile
    # 182 MB
    mem_limit: 182000000
    container_name: "archivematica-mcp-server"
    entrypoint: bash -c "while [ true ]; do sleep 10; done"
    #env_file: /mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/secrets/secrets-env.am-server.properties
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/arquivo-atom-dsv/archivematica-atom-dip:/opt/dip:rw" # Upload DIP
    links:
      - "gearmand"
      - "archivematicassdsv"

  archivematica-mcp-client:
    # image: registry.senado.leg.br/adm/archivematica/archivematica-mcp-client:1.13.2
    build: 
      context: .
      dockerfile: MCPClient.Dockerfile
    # 1.24 GB
    mem_limit: 1240000000
    #env_file: /mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/secrets/secrets-env.am-client.properties
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/arquivo-atom-dsv/archivematica-atom-dip:/opt/dip:rw" # Upload DIP
    links:
      - "fits"
      - "clamavd"
      - "gearmand"
      - "elasticsearch"
      - "archivematicassdsv"

  #archivematica-dashboard:
  archivematicadsv:
    # image: registry.senado.leg.br/adm/archivematica/archivematica-dashboard:1.13.2
    build: 
      context: .
      dockerfile: dashboard.Dockerfile
    # 520 MB
    mem_limit: 520000000
    #env_file: /mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/secrets/secrets-env.am-dashboard.properties
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "nginx"
      - "gearmand"
      - "elasticsearch"
      - "archivematicassdsv"

  #archivematica-storage-service:
  archivematicassdsv:
    image: archivematica-ss:latest
    # 225 MB
    mem_limit: 225000000
    #env_file: /mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/secrets/secrets-env.am-storage.properties
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      # - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      #  "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
      # - "/mnt/archivematica_transferencia/arquivo-am-dsv:/opt/arquivo:rw"
    links:
      - "nginx"

#  shell:
#    image: ubuntu:latest
#    # 120 MB
#    mem_limit: 120000000
#    container_name: "shell"
#    #env_file: /mnt/containers-volumes/desenvolvimento/arquivo-am-dsv/secrets/secrets-env.am-client.properties
#    environment:
#      TZ: "America/Sao_Paulo"
#    command: ["bash", "-c", "sleep 30000"]
#    volumes:
#      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
#      - "/mnt/containers-volumes/desenvolvimento/arquivo-am-dsv:/mnt:rw"
#      - "/mnt/archivematica_transferencia/arquivo-am-dsv:/opt/arquivo:rw"
#    labels:
#      io.rancher.scheduler.affinity:host_label: role-coarq=true
#      io.rancher.container.pull_image: always
#      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}